### PR TITLE
Catalyst

### PR DESCRIPTION
**Pull request by alex-taffe**
#80 MUST be merged first

This completes #76. The Mac app has custom preferences, help, and other features to better integrate it with the platform. In addition, the seismic activity has been disabled due to the lack of accelerometer, as has the TimeLapse Pro icon due to no available Mac app. Peekaboo and motion detection have also been disabled due to #75.

This pull request also does things like move to a native UISplitView to enhance the experience on iPad (especially when using side by side apps in iOS 13) and Mac. This does change the UX of the sidebar slightly, but it is overall for the better. The dark mode color scheme has also been improved, as well as responds to system changes (finishes #78)

### CODE REVIEW

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe I've merged #80, so hopefully, this unblocks you.

Also, could you expand a bit more on "The dark mode color scheme has also been improved", what exactly has changed relating to that?

**Comment by alex-taffe** [comment]
Thanks Ross, I’m still working on this so it’s not quite ready to merge yet, but once it’s done I’ll finalize the pull request and let you know. As for the improved dark mode color scheme. That was somewhat of a poorly named commit message. On macOS, there’s some buttons and logos that are differing from the iOS version. That commit was just me noticing that they were not being properly colored in dark mode on macOS and fixing the issues

**Comment by alex-taffe** [comment]
`AVAudioSession.sharedInstance().outputVolume` is returning 1.0 on macOS regardless of what the system volume is actually set to. In communication with apple to find a resolution

**Comment by alex-taffe** [comment]
@Ross-Gibson this should be ready to go. There are two different targets for macOS to facilitate removing the GPUImage library. Long term for the application itself, wouldn't necessarily mind having the Mac version on my developer account just so I have something interesting there but understand if that's not doable

**Comment by alex-taffe** [comment]
Wait a bit to test this, found a bit of a nasty bug with dark mode

**Comment by Ross-Gibson** [comment]
@alex-taffe sure, just let me know when it's ready to go :)

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe how's this coming along, is it ready to review yet? Or, do you need any help to discuss issues?

**Comment by alex-taffe** [comment]
@Ross-Gibson sorry about the delay, it was finals season and I was a bit busy. I'm going to try to get this wrapped up this weekend

**Comment by alex-taffe** [comment]
@Ross-Gibson sorry for the delay on this. Finally got around to wrapping everything up.

**Comment by alex-taffe** [comment]
@Ross-Gibson just making sure you saw this

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe, so sorry - I did see this and then it slipped my mind with everything over Christmas and New Year. I'll try to find time today to take a look. Thanks!

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe this all looks great. Just a few minor issues that I've noticed:

1. In TimeWarp the handle for one of the drag points loads out of the bounds of the view, and there is no way for you to grab it. (I'm not sure how to reproduce this, it happened once, but I can't repeat it).
2. It's not obvious how the text field inputs work in modes like Timelapse, Star Trail etc. When you select it, the value changes to 0 and it highlights blue, but when you tap away in the background the value changes back to its original value, but the field remains blue.
3. If you open the Preferences, the Sensor Delay and Sensor Reset Delay have a grey side panel next to them. I think we should hide this, and just have a white background.
4. It's possible to open the Preferences multiple times, each time you select it a new window opens. I think if it's already open then it should just bring that window to the foreground.

**Comment by Ross-Gibson** [comment]
Also, testing on iOS I've noticed:

5. There is a back button in the header for each mode. I find this a little confusing, maybe using a menu icon would make more sense? Or, when the app opens it should load the menu as the default screen, rather than Simple Cable Release. Any thoughts?
6. When you rotate the device to landscape it's not possible to open the menu.

On the Mac app:

7. I don't think the tutorial makes much sense with the iPhone images. Maybe we hide it from the Mac app for now?
8. There is no way to access the Cable Selector, or the Feedback and Support section. Maybe the Help menu item should be used to open this instead of the tutorial?

**Comment by alex-taffe** [comment]
@Ross-Gibson I'll take a look!

**Pull request closed without merging**
