### PR TITLE
Upgrade app to support iOS 11 and iPhone X

### PR DESCRIPTION
**Pull request by alex-taffe**
This pull request accomplishes a number of things:
- Converts the project to Swift 4
- Updates the project settings to that recommended by Xcode 9
- Allows the app to render properly on iPhone X
- Enables automatic signing management
- Enables cocoapod framework usage
- Removes Pods folder from the repo (best practice for open source software)
- Increases the minimum iOS version to 10
- Fixes a compile issue with fonts (currently using system default)
- Fixes many compiler warnings

Known issues:
- Pebble app may be non functional (cannot test)
- Font is wrong
- Time warp causes the app to freeze (#12)

### CODE REVIEW

**Comment by alex-taffe** [comment]
@Ross-Gibson is this repo still be maintained?

**Comment by alex-taffe** [comment]
@Ross-Gibson awesome, glad to hear it! Triggertrap has long been one of my favorite apps and I didn’t want it to fade into abandonware so I took the time to actually get it modernized and working with the newest Swift compiler and iPhones. It isn’t perfect yet because I’m still working on piecing together how the whole app interacts but it works. I’m also trying to get CPU use down so that battery life isn’t killed (during stuff like timer release 100% of 1 core is being used which isn’t awesome)

**Comment by alex-taffe** [comment]
I also want to clean up the onboarding process to remove links to the old trigger trap website and inform people what the purpose of the app is. I’d also love to be able to put the app back on the App Store somehow but I just don’t know what legality issues are part of that

**Comment by Ross-Gibson** [comment]
@alex-taffe that would be great. I'd suggest perhaps opening separate pull requests for that work, I'll then do my best to review them as soon as possible. It would be great to get this project back up-to-speed again, it's been a while since I've worked on it myself.

At the moment the app is in a state that we can't publish it to the App Store, because my old ross@triggertrap.com email has been closed down (hence why I did not receive the notification that you'd done this work on the repo). Because of this I'm unable to access iTunes Connect for the Triggertrap page. I'm in the process of sorting this out, and I'll keep you informed.

In the meantime, keep up the good work. Thanks.

**Comment by alex-taffe** [comment]
@Ross-Gibson Will do, I’ll just make feature branches for everything else. And ahh ok, well hopefully we can get it back up for everyone!

**Comment by alex-taffe** [comment]
@Ross-Gibson is the trigger trap timelapse pro app open source? I’d love to get that updated too

**Comment by alex-taffe** [comment]
Also should we remove the pebble watch app? Pebble is now dead so I'm not sure it's worth having. Also, we will probably have to at least temporarily disable the Apple Watch because it is a watchOS 1 app

**Comment by Ross-Gibson** [comment]
I don't have a pebble for testing, and as it's now dead I'd agree - removing it would be a good idea. Also, in regards to Triggertrap Timelapse Pro, it's not currently Open Source. That app was transferred to myself when I left Triggertrap. If you'd like to discuss potentially collaborating together on that project then we could discuss that away from this thread.

**Comment by alex-taffe** [comment]
Yeah I would be open to helping with that, I'll shoot you an email

**Pull request merged**
