### PR TITLE
Detection mode zoom

### PR DESCRIPTION
**Pull request by alex-taffe**
Finishes #53

### CODE REVIEW

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe, great start!

While using this I have noticed a few crashes. Mainly on the Motion Sensor mode. Launching the app for the first time and navigating to Motion Sensor seems a bit slow, and the same if you have the mode open (but not running) and then background the app. The crash I've been seeing appears to happen if you zoom in quickly and then zoom back out.

The crash appears to originate from `GPUImageFrameBuffer.m` line 152. We get a returned `CVReturn` error of type `1`. I'm not sure what this is yet, but I presume we are not handling this error correctly, or that we have passed incorrect parameters to get that error.

I'm busy today, but I'll try and have a look into this tomorrow to see if I can understand any more.

Great work though. I think this feature will be liked by the users!

**Comment by alex-taffe** [comment]
@Ross-Gibson it opens slowly only if you have it running from Xcode. There's an issue within the GPUImage library itself where it's doing a UI update from a background thread. This issue details it BradLarson/GPUImage#2512. If you disable the background thread checker in Xcode (Edit scheme>run>diagnostics>main thread checker), it will launch at normal speed (same can be observed if you archive the app and export it, then install to a phone).

As for the crash, I was experiencing that very briefly due to bad code initially yesterday, but fixed it and hadn't had it happen again (still can't reproduce) so I'm not sure what's up with that

**Comment by Ross-Gibson** [comment]
Hey @alex-taffe, thanks for the info. I'll re-test this with the background thread checker disabled and investigate the crash a bit further.

**Comment by alex-taffe** [comment]
This is all going to be rewritten as a part of #75 anyways, so closing

**Pull request closed without merging**
